function test_Test(){var l='',F='" for "gwt:onLoadErrorFn"',D='" for "gwt:onPropertyErrorFn"',n='"><\/script>',p='#',r='/',Fb='<script defer="defer">test_Test.onInjectionDone(\'test.Test\')<\/script>',dc='<script id="',Db='<script language="javascript" src="',A='=',q='?',C='Bad handler "',Bb='DOMContentLoaded',tb="GWT module 'test.Test' needs to be (re)compiled, please run a compile or use the Compile/Browse button in hosted mode",o='SCRIPT',cc='__gwt_marker_test.Test',s='base',nb='begin',cb='bootstrap',u='clear.cache.gif',z='content',bc='end',mb='gecko',ob='gecko1_8',yb='gwt.hybrid',ub='gwt/standard/standard.css',E='gwt:onLoadErrorFn',B='gwt:onPropertyErrorFn',y='gwt:property',Ab='head',rb='hosted.html?test_Test',zb='href',lb='ie6',kb='ie8',ab='iframe',t='img',bb="javascript:''",vb='link',qb='loadExternalRefs',v='meta',eb='moduleRequested',ac='moduleStartup',jb='msie',w='name',gb='opera',Cb='pagebus.js',Eb='pagebus.js"><\/script>',db='position:absolute;width:0;height:0;border:none',wb='rel',ib='safari',sb='selectingPermutation',x='startup',xb='stylesheet',m='test.Test',pb='unknown',fb='user.agent',hb='webkit';var fc=window,k=document,ec=fc.__gwtStatsEvent?function(a){return fc.__gwtStatsEvent(a)}:null,zc,pc,kc,jc=l,sc={},Cc=[],yc=[],ic=[],vc,xc;ec&&ec({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:nb});if(!fc.__gwt_stylesLoaded){fc.__gwt_stylesLoaded={}}if(!fc.__gwt_scriptsLoaded){fc.__gwt_scriptsLoaded={}}function oc(){var b=false;try{b=fc.external&&(fc.external.gwtOnLoad&&fc.location.search.indexOf(yb)==-1)}catch(a){}oc=function(){return b};return b}
function rc(){if(zc&&pc){var c=k.getElementById(m);var b=c.contentWindow;if(oc()){b.__gwt_getProperty=function(a){return lc(a)}}test_Test=null;b.gwtOnLoad(vc,m,jc);ec&&ec({moduleName:m,subSystem:x,evtGroup:ac,millis:(new Date()).getTime(),type:bc})}}
function mc(){var j,h=cc,i;k.write(dc+h+n);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=o){j=j.previousSibling}function f(b){var a=b.lastIndexOf(p);if(a==-1){a=b.length}var c=b.indexOf(q);if(c==-1){c=b.length}var d=b.lastIndexOf(r,Math.min(c,a));return d>=0?b.substring(0,d+1):l}
;if(j&&j.src){jc=f(j.src)}if(jc==l){var e=k.getElementsByTagName(s);if(e.length>0){jc=e[e.length-1].href}else{jc=f(k.location.href)}}else if(jc.match(/^\w+:\/\//)){}else{var g=k.createElement(t);g.src=jc+u;jc=f(g.src)}if(i){i.parentNode.removeChild(i)}}
function wc(){var f=document.getElementsByTagName(v);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(w),b;if(h){if(h==y){b=e.getAttribute(z);if(b){var i,c=b.indexOf(A);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}sc[h]=i}}else if(h==B){b=e.getAttribute(z);if(b){try{xc=eval(b)}catch(a){alert(C+b+D)}}}else if(h==E){b=e.getAttribute(z);if(b){try{vc=eval(b)}catch(a){alert(C+b+F)}}}}}}
function lc(d){var e=yc[d](),b=Cc[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(xc){xc(d,a,e)}throw null}
var nc;function qc(){if(!nc){nc=true;var a=k.createElement(ab);a.src=bb;a.id=m;a.style.cssText=db;a.tabIndex=-1;k.body.appendChild(a);ec&&ec({moduleName:m,subSystem:x,evtGroup:ac,millis:(new Date()).getTime(),type:eb});a.contentWindow.location.replace(jc+Ac)}}
yc[fb]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(gb)!=-1){return gb}else if(d.indexOf(hb)!=-1){return ib}else if(d.indexOf(jb)!=-1){if(document.documentMode>=8){return kb}else{var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){var e=b(c);if(e>=6000){return lb}}}}else if(d.indexOf(mb)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return ob}return mb}return pb};Cc[fb]={gecko:0,gecko1_8:1,ie6:2,ie8:3,opera:4,safari:5};test_Test.onScriptLoad=function(){if(nc){pc=true;rc()}};test_Test.onInjectionDone=function(){zc=true;ec&&ec({moduleName:m,subSystem:x,evtGroup:qb,millis:(new Date()).getTime(),type:bc});rc()};mc();var Ac;if(oc()){if(fc.external.initModule&&fc.external.initModule(m)){fc.location.reload();return}Ac=rb}wc();ec&&ec({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:sb});if(!Ac){try{alert(tb);return}catch(a){return}}var uc;function tc(){if(!kc){kc=true;if(!__gwt_stylesLoaded[ub]){var a=k.createElement(vb);__gwt_stylesLoaded[ub]=a;a.setAttribute(wb,xb);a.setAttribute(zb,jc+ub);k.getElementsByTagName(Ab)[0].appendChild(a)}rc();if(k.removeEventListener){k.removeEventListener(Bb,tc,false)}if(uc){clearInterval(uc)}}}
if(k.addEventListener){k.addEventListener(Bb,function(){qc();tc()},false)}var uc=setInterval(function(){if(/loaded|complete/.test(k.readyState)){qc();tc()}},50);ec&&ec({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:bc});ec&&ec({moduleName:m,subSystem:x,evtGroup:qb,millis:(new Date()).getTime(),type:nb});if(!__gwt_scriptsLoaded[Cb]){__gwt_scriptsLoaded[Cb]=true;document.write(Db+jc+Eb)}k.write(Fb)}
test_Test();